"""Add column not null, remove index=true on primary key

Revision ID: 61f33a3a69f0
Revises: 1d09b01ff002
Create Date: 2024-01-09 22:59:15.028257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f33a3a69f0'
down_revision = '1d09b01ff002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('deleted_post', schema=None) as batch_op:
        batch_op.drop_index('ix_deleted_post_id')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_id', ['id'], unique=False)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('deleted_post', schema=None) as batch_op:
        batch_op.create_index('ix_deleted_post_id', ['id'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
