"""Make slug not nullable

Revision ID: 798dd62587ef
Revises: a982012a9cbb
Create Date: 2024-01-10 19:09:09.449979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798dd62587ef'
down_revision = 'a982012a9cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
