"""empty message

Revision ID: a257a06a1e3c
Revises: 45c8e93d6960
Create Date: 2022-01-04 18:22:31.546761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a257a06a1e3c'
down_revision = '45c8e93d6960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    op.drop_column('post', 'related_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('related_posts', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###
