"""Remove nullable on category slug

Revision ID: a982012a9cbb
Revises: 61f33a3a69f0
Create Date: 2024-01-09 23:02:45.843012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a982012a9cbb'
down_revision = '61f33a3a69f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deleted_post', schema=None) as batch_op:
        batch_op.drop_index('ix_deleted_post_id')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_id', ['id'], unique=False)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('deleted_post', schema=None) as batch_op:
        batch_op.create_index('ix_deleted_post_id', ['id'], unique=False)

    # ### end Alembic commands ###
